{
    "status": "ERROR",
    "result": "That user does not exist.",
    "errorCode": 110001,
    "errorInfo": {
        "description": "User requested a user that could not be found.",
        "stack": "Error: User not found.\n    at userQuerySuccessCallback (/var/app/versions/v1/app/resources/users/methods/show.js:38:17)\n    at _fulfilled (/var/app/node_modules/q/q.js:787:54)\n    at self.promiseDispatch.done (/var/app/node_modules/q/q.js:816:30)\n    at Promise.promise.promiseDispatch (/var/app/node_modules/q/q.js:749:13)\n    at /var/app/node_modules/q/q.js:557:44\n    at flush (/var/app/node_modules/q/q.js:108:17)\n    at /var/app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31\n    at process._tickDomainCallback (node.js:459:13)\n    at process.<anonymous> (/var/app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)",
        "data": null
    }
}
